src/main/java/com/cgi/osd/transactiondemo/logic/BookingServiceBean.java
package com.cgi.osd.transactiondemo.logic;

import java.util.List;
import java.util.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;
import com.cgi.osd.transactiondemo.logic.exception.PersistenceOperationException;
import com.cgi.osd.transactiondemo.persistence.PersistenceManager;

/**
 * This class is responsible for implementing the booking services.
 *
 */

@ApplicationScoped
public class BookingServiceBean implements BookingService {

    @Inject
    Logger logger;

    @Inject
    private PersistenceManager persistenceManager;

    @Override
    public List<SeatDO> getAllSeats() throws PersistenceOperationException {
	final List<SeatDO> seats = this.persistenceManager.getAllSeats();
	return seats;
    }

}

src/main/java/com/cgi/osd/transactiondemo/persistence/PersistenceManagerBean.java
package com.cgi.osd.transactiondemo.persistence;

import java.util.List;

import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;
import javax.inject.Inject;
import javax.interceptor.Interceptors;
import javax.persistence.EntityManager;
import javax.persistence.LockModeType;
import javax.persistence.TypedQuery;

import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;

/**
 * This class is responsible for implementing methods for persistence handling. All methods are thread safe.
 *
 */
@Stateless
@TransactionManagement(TransactionManagementType.CONTAINER)
@TransactionAttribute(TransactionAttributeType.NEVER)
@Interceptors(ExceptionInterceptor.class)
public class PersistenceManagerBean implements PersistenceManager {

    @Inject
    private EntityManager em;

    @Inject
    private PersistenceObjectFactory objectFactory;

    @Override
    @TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)
    public List<SeatDO> getAllSeats() {
	final List<Seat> dbResult = fetchAllSeats();
	final List<SeatDO> result = this.objectFactory.createSeatDOList(dbResult);
	return result;
    }

    private List<Seat> fetchAllSeats() {
	final TypedQuery<Seat> query = this.em.createNamedQuery("Seat.findAll", Seat.class);
	query.setLockMode(LockModeType.OPTIMISTIC);
	final List<Seat> dbResult = query.getResultList();
	return dbResult;
    }

}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/BookingController.java
package com.cgi.osd.transactiondemo.presentation.gui;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.cgi.osd.transactiondemo.logic.domainobject.SeatDO;

/**
 * This class is responsible for the controller part of the MVC pattern for the booking process.
 *
 *
 */
@SessionScoped
@Named
public class BookingController implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    private BookingData bookingData;

    public List<SeatDO> getAllSeats() {
	return this.bookingData.getAllSeats();
    }
}

src/main/webapp/WEB-INF/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>${artifactId}</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<h:outputStylesheet name="css/screen.css" />
</h:head>
<h:body>
	<h:outputStylesheet name="css/primefacesoverride.css" />
	<div id="container">
		<div id="header">
			<img src="resources/gfx/wildfly-banner-1180px.png" id="headbanner" />
		</div>
		<div id="content">
			<ui:insert name="content">
                    [Template content will be inserted here]
         </ui:insert>
		</div>
		<div id="aside">
			<p>Studentprojekt för att utveckla ett biljettbokningsssytem.</p>
			<p>Mycket nöje med Wildfly.</p>
		</div>
		<div id="footer">
			<p>
				Projektet använder JSF med PrimeFaces.<br />
			</p>
		</div>
	</div>
       <script language="javascript" type="text/javascript" src="transactiondemo.js"/>
</h:body>
</html>

src/main/webapp/booking.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<h:form id="seatBookingForm" styleClass="basicform">
		<p:panelGrid columns="1">
			<p:panel>
				<p:dataTable id="bookingTable" var="seats" scrollable="true" scrollHeight="393" value="#{bookingController.allSeats}">
					<p:column headerText="Platsnummer" class="centeredColumn">
						<h:outputText value="#{seats.seatNumber}" />
					</p:column>
				</p:dataTable>
			</p:panel>
			<f:facet name="footer">
				<p:messages id="bookingMessage" showDetail="true" autoUpdate="true" closable="true" />
			</f:facet>
		</p:panelGrid>
	</h:form>
	
</ui:composition>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/templates/default.xhtml">
	<ui:define name="content">

		<p:tabView dynamic="true" cache = "false">
			<p:tab title="Boka">
				<ui:include src="/booking.xhtml" />
			</p:tab>
		</p:tabView>


	</ui:define>
</ui:composition>